#!/usr/bin/env ruby
file="~/.gitshots/#{Time.now.strftime('%Y%m%d-%H%M%S')}.jpg"
unless File.directory?(File.expand_path("../../rebase-merge", __FILE__))
  puts "Taking capture into #{file}!"
  system "imagesnap -q -w 3 #{file} &"
end
exit 0
